name = "NSF_LEAPS"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["NSFLEAPS"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "082e2d37e8b0463410cdb532e111cd43d5a66174"

[[require]]
name = "checkdecls"
git = "https://github.com/PatrickMassot/checkdecls.git"

[[require]]
name = "«doc-gen4»"
git = "https://github.com/leanprover/doc-gen4"
rev = "main"
[[lean_lib]]
name = "NSFLEAPS"
